# Generated by Django 6.0.6 on 2026-08-13 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.AddField(
            model_name='complaint',
            name='raised_by_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
