# Generated by Django 6.0.6 on 2026-08-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('department_name', models.CharField(db_column='DepartmentName', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_column='Email', max_length=150, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('faculty_id', models.CharField(db_column='FacultyID', max_length=50, unique=True)),
                ('department', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('department', models.OneToOneField(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HOD',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('register_number', models.CharField(db_column='RegisterNumber', max_length=50, unique=True)),
                ('study_year', models.IntegerField(db_column='StudyYear')),
                ('phone_number', models.CharField(db_column='PhoneNumber', max_length=15)),
                ('department', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
