# Generated by Django 6.0.7 on 2026-08-12 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('department_name', models.CharField(db_column='DepartmentName', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='PasswordHash', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, db_column='RoleID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('employee_id', models.CharField(db_column='EmployeeID', max_length=50, unique=True)),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='dean_profile', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
            options={
                'db_table': 'Deans',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('faculty_id', models.CharField(db_column='FacultyID', max_length=50, unique=True)),
                ('department', models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('department', models.OneToOneField(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='hod_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HOD',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('employee_id', models.CharField(db_column='EmployeeID', max_length=50, unique=True)),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='principal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Principal',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='FullName', max_length=150)),
                ('register_number', models.CharField(db_column='RegisterNumber', max_length=50, unique=True)),
                ('study_year', models.IntegerField(blank=True, db_column='StudyYear', null=True)),
                ('phone_number', models.CharField(blank=True, db_column='PhoneNumber', max_length=15, null=True)),
                ('department', models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('user', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
