# Generated by Django 6.0.7 on 2026-08-15 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
