# Generated by Django 6.0.7 on 2026-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_hod_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CategoryName', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
    ]
