# Generated by Django 6.0.7 on 2026-08-15 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp')),
                ('action', models.CharField(db_column='Action', max_length=255)),
                ('ip_address', models.CharField(blank=True, db_column='IPAddress', max_length=50, null=True)),
                ('status', models.CharField(db_column='Status', default='Success', max_length=50)),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SystemLogs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
