# Generated by Django 6.0.7 on 2026-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('claim_id', models.AutoField(db_column='ClaimID', primary_key=True, serialize=False)),
                ('item_type', models.CharField(db_column='ItemType', max_length=10)),
                ('item_id', models.IntegerField(db_column='ItemID')),
                ('proof_description', models.TextField(db_column='ProofDescription')),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_column='RequestedAt')),
            ],
            options={
                'db_table': 'ClaimRequests',
            },
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_id', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('description', models.TextField(db_column='Description')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('date_found', models.DateField(db_column='DateFound')),
                ('photo_url', models.CharField(blank=True, db_column='PhotoURL', max_length=500, null=True)),
                ('contact_details', models.CharField(blank=True, db_column='ContactDetails', max_length=100, null=True)),
                ('status', models.CharField(db_column='Status', default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'FoundItems',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('item_id', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('description', models.TextField(db_column='Description')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('date_reported', models.DateField(db_column='DateReported')),
                ('photo_url', models.CharField(blank=True, db_column='PhotoURL', max_length=500, null=True)),
                ('contact_details', models.CharField(blank=True, db_column='ContactDetails', max_length=100, null=True)),
                ('status', models.CharField(db_column='Status', default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'LostItems',
            },
        ),
    ]
