# Generated by Django 6.0.7 on 2026-08-12 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lostfound', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='claimed_by',
            field=models.ForeignKey(db_column='ClaimedBy', on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='founditem',
            name='department',
            field=models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reported_by',
            field=models.ForeignKey(db_column='ReportedBy', on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='department',
            field=models.ForeignKey(blank=True, db_column='DepartmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='reported_by',
            field=models.ForeignKey(db_column='ReportedBy', on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
